name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      #Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      #Step 2: Set up PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Specify the PHP version
          extensions: mbstring, mysqli
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      #Step 3: Install Composer dependencies
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      #Step 4: Create a .env file for the database connection
      - name: Create .env file
        run: |
          echo "DB_CONNECTION=mysql" > .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=testing_db" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      #Step 5: Run database migrations (if applicable)
      - name: Run migrations
        run: php artisan migrate

      #Step 6: Run tests
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --testdox

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      #Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      #Step 2: Deploy the application (you can use rsync, FTP, or other deployment tools)
      #For example, deploying to a server via SSH
      - name: Deploy to Server
        run: |
          echo "Deploying application to server..."
          ssh user@your-server.com 'cd /path-to-your-app && git pull origin main'
